use std::collections::HashMap;

#[derive(Debug)]
pub struct Instruction {
    pub code: u8,
    pub mnemonic: Mnemonic,
    pub length: usize, // in bytes
    pub cycles: usize,
}

impl Instruction {
    fn new(code: u8, mnemonic: Mnemonic, cycles: usize, length: usize) -> Self {
        Self {
            code,
            mnemonic,
            length,
            cycles,
        }
    }
}

#[allow(non_camel_case_types)]
#[derive(Debug, PartialEq)]
pub enum Mnemonic {
    NYI,
    ILLEGAL_EC,
    LD_A_n8,
    LD_D_L,
    ADC_A_L,
    OR_A_HL,
    RET_Z,
    DEC_E,
    LD_E_C,
    XOR_A_H,
    LDH_a8_A,
    LD_SP_HL,
    JP_a16,
    INC_C,
    LD_L_L,
    DEC_H,
    LD_H_A,
    PREFIX,
    ADD_HL_SP,
    RET_NC,
    LD_H_D,
    INC_A,
    LD_HL_B,
    INC_BC,
    LD_HL_E,
    RST_00,
    LD_D_C,
    SUB_A_D,
    JP_Z_a16,
    LDH_A_a8,
    SUB_A_L,
    LD_a16_SP,
    LD_D_D,
    LD_C_E,
    XOR_A_B,
    LD_D_E,
    ADC_A_B,
    JR_Z_e8,
    ILLEGAL_DB,
    JR_NC_e8,
    LD_HL_n16,
    INC_D,
    OR_A_D,
    LD_A_L,
    LD_B_C,
    LD_A_HL,
    ADC_A_C,
    ILLEGAL_FC,
    LD_L_A,
    LD_L_H,
    LD_C_n8,
    LD_HL_A,
    DEC_A,
    RST_18,
    JP_NZ_a16,
    SCF,
    RST_10,
    ADC_A_D,
    LD_HL_n8,
    DEC_C,
    JP_HL,
    RETI,
    ILLEGAL_EB,
    ADD_A_HL,
    ILLEGAL_F4,
    LD_C_C,
    ILLEGAL_E3,
    ILLEGAL_DD,
    LD_H_B,
    LD_A_E,
    SBC_A_B,
    SBC_A_D,
    LD_DE_A,
    SUB_A_C,
    LD_DE_n16,
    AND_A_L,
    LD_HL_SP_e8,
    DEC_D,
    XOR_A_A,
    CP_A_B,
    LD_C_A,
    ADD_HL_HL,
    LD_B_A,
    RST_38,
    INC_L,
    SBC_A_E,
    DEC_HL,
    ADC_A_n8,
    SUB_A_HL,
    RET,
    LD_B_HL,
    CALL_NZ_a16,
    SUB_A_n8,
    AND_A_HL,
    CALL_C_a16,
    LD_a16_A,
    JR_e8,
    SUB_A_A,
    AND_A_E,
    ADD_A_C,
    LD_C_HL,
    LD_A_DE,
    LD_E_B,
    LD_L_E,
    LD_HL_D,
    DAA,
    LD_A_C,
    CP_A_A,
    HALT,
    ADD_A_E,
    AND_A_B,
    POP_DE,
    POP_AF,
    DEC_SP,
    LD_C_H,
    SUB_A_E,
    LD_H_n8,
    EI,
    CP_A_H,
    OR_A_H,
    CP_A_L,
    RLCA,
    NOP,
    RRCA,
    RST_20,
    DEC_L,
    LD_HL_C,
    ADD_SP_e8,
    SBC_A_C,
    ADC_A_H,
    RRA,
    RET_C,
    ILLEGAL_ED,
    LD_D_n8,
    STOP_n8,
    LD_E_H,
    INC_SP,
    LD_E_A,
    LD_H_H,
    AND_A_D,
    CP_A_C,
    CP_A_D,
    INC_HL,
    LD_H_E,
    CP_A_HL,
    ILLEGAL_FD,
    ADC_A_HL,
    INC_B,
    XOR_A_L,
    RST_28,
    OR_A_A,
    LD_SP_n16,
    OR_A_B,
    ADD_A_H,
    OR_A_E,
    LD_D_B,
    LD_A_D,
    INC_E,
    PUSH_HL,
    LD_D_A,
    LD_H_HL,
    DEC_DE,
    XOR_A_D,
    ADD_A_L,
    SBC_A_HL,
    SUB_A_H,
    INC_DE,
    ADD_A_B,
    LD_L_B,
    LD_H_C,
    AND_A_C,
    LD_E_HL,
    LD_B_H,
    LD_B_B,
    CALL_a16,
    RST_30,
    LD_H_L,
    LD_BC_A,
    JP_NC_a16,
    LD_D_H,
    JP_C_a16,
    SBC_A_H,
    AND_A_H,
    PUSH_BC,
    ADD_A_D,
    DI,
    RST_08,
    LD_C_D,
    SBC_A_n8,
    LD_B_n8,
    AND_A_A,
    ADC_A_E,
    CALL_NC_a16,
    JR_NZ_e8,
    DEC_BC,
    SBC_A_L,
    ADD_A_n8,
    LD_B_D,
    PUSH_DE,
    XOR_A_n8,
    LD_B_L,
    LD_A_H,
    CPL,
    LD_E_n8,
    INC_H,
    AND_A_n8,
    LD_D_HL,
    ADC_A_A,
    CP_A_n8,
    PUSH_AF,
    LD_A_BC,
    LD_A_A,
    LD_HL_H,
    LD_C_L,
    OR_A_C,
    POP_HL,
    ILLEGAL_E4,
    LD_L_HL,
    OR_A_L,
    LD_E_L,
    LD_E_E,
    LD_A_a16,
    LD_E_D,
    XOR_A_HL,
    ADD_HL_BC,
    ADD_HL_DE,
    SUB_A_B,
    RET_NZ,
    OR_A_n8,
    POP_BC,
    XOR_A_C,
    LD_L_n8,
    CALL_Z_a16,
    XOR_A_E,
    LD_L_C,
    RLA,
    SBC_A_A,
    CCF,
    LD_L_D,
    LD_C_B,
    ILLEGAL_D3,
    LD_BC_n16,
    ADD_A_A,
    LD_HL_L,
    LD_B_E,
    JR_C_e8,
    DEC_B,
    CP_A_E,
    LD_A_B,
}

impl From<u8> for Instruction {
    fn from(value: u8) -> Self {
        match value {
            0xEC => Self::new(value, Mnemonic::ILLEGAL_EC, 4, 0),
            0x3E => Self::new(value, Mnemonic::LD_A_n8, 8, 1),
            0x55 => Self::new(value, Mnemonic::LD_D_L, 4, 0),
            0x8D => Self::new(value, Mnemonic::ADC_A_L, 4, 0),
            0xB6 => Self::new(value, Mnemonic::OR_A_HL, 8, 0),
            0xC8 => Self::new(value, Mnemonic::RET_Z, 20, 0),
            0x1D => Self::new(value, Mnemonic::DEC_E, 4, 0),
            0x59 => Self::new(value, Mnemonic::LD_E_C, 4, 0),
            0xAC => Self::new(value, Mnemonic::XOR_A_H, 4, 0),
            0xE0 => Self::new(value, Mnemonic::LDH_a8_A, 12, 1),
            0xF9 => Self::new(value, Mnemonic::LD_SP_HL, 8, 0),
            0xC3 => Self::new(value, Mnemonic::JP_a16, 16, 2),
            0x0C => Self::new(value, Mnemonic::INC_C, 4, 0),
            0x6D => Self::new(value, Mnemonic::LD_L_L, 4, 0),
            0x25 => Self::new(value, Mnemonic::DEC_H, 4, 0),
            0x67 => Self::new(value, Mnemonic::LD_H_A, 4, 0),
            0xCB => Self::new(value, Mnemonic::PREFIX, 4, 0),
            0x39 => Self::new(value, Mnemonic::ADD_HL_SP, 8, 0),
            0xD0 => Self::new(value, Mnemonic::RET_NC, 20, 0),
            0x62 => Self::new(value, Mnemonic::LD_H_D, 4, 0),
            0x3C => Self::new(value, Mnemonic::INC_A, 4, 0),
            0x70 => Self::new(value, Mnemonic::LD_HL_B, 8, 0),
            0x03 => Self::new(value, Mnemonic::INC_BC, 8, 0),
            0x73 => Self::new(value, Mnemonic::LD_HL_E, 8, 0),
            0xC7 => Self::new(value, Mnemonic::RST_00, 16, 0),
            0x51 => Self::new(value, Mnemonic::LD_D_C, 4, 0),
            0x92 => Self::new(value, Mnemonic::SUB_A_D, 4, 0),
            0xCA => Self::new(value, Mnemonic::JP_Z_a16, 16, 2),
            0xF0 => Self::new(value, Mnemonic::LDH_A_a8, 12, 1),
            0x95 => Self::new(value, Mnemonic::SUB_A_L, 4, 0),
            0x08 => Self::new(value, Mnemonic::LD_a16_SP, 20, 2),
            0x52 => Self::new(value, Mnemonic::LD_D_D, 4, 0),
            0x4B => Self::new(value, Mnemonic::LD_C_E, 4, 0),
            0xA8 => Self::new(value, Mnemonic::XOR_A_B, 4, 0),
            0x53 => Self::new(value, Mnemonic::LD_D_E, 4, 0),
            0x88 => Self::new(value, Mnemonic::ADC_A_B, 4, 0),
            0x28 => Self::new(value, Mnemonic::JR_Z_e8, 12, 1),
            0xDB => Self::new(value, Mnemonic::ILLEGAL_DB, 4, 0),
            0x30 => Self::new(value, Mnemonic::JR_NC_e8, 12, 1),
            0x21 => Self::new(value, Mnemonic::LD_HL_n16, 12, 2),
            0x14 => Self::new(value, Mnemonic::INC_D, 4, 0),
            0xB2 => Self::new(value, Mnemonic::OR_A_D, 4, 0),
            0x7D => Self::new(value, Mnemonic::LD_A_L, 4, 0),
            0x41 => Self::new(value, Mnemonic::LD_B_C, 4, 0),
            0x7E => Self::new(value, Mnemonic::LD_A_HL, 8, 0),
            0x89 => Self::new(value, Mnemonic::ADC_A_C, 4, 0),
            0xFC => Self::new(value, Mnemonic::ILLEGAL_FC, 4, 0),
            0x6F => Self::new(value, Mnemonic::LD_L_A, 4, 0),
            0x6C => Self::new(value, Mnemonic::LD_L_H, 4, 0),
            0x0E => Self::new(value, Mnemonic::LD_C_n8, 8, 1),
            0x77 => Self::new(value, Mnemonic::LD_HL_A, 8, 0),
            0x3D => Self::new(value, Mnemonic::DEC_A, 4, 0),
            0xDF => Self::new(value, Mnemonic::RST_18, 16, 0),
            0xC2 => Self::new(value, Mnemonic::JP_NZ_a16, 16, 2),
            0x37 => Self::new(value, Mnemonic::SCF, 4, 0),
            0xD7 => Self::new(value, Mnemonic::RST_10, 16, 0),
            0x8A => Self::new(value, Mnemonic::ADC_A_D, 4, 0),
            0x36 => Self::new(value, Mnemonic::LD_HL_n8, 12, 1),
            0x0D => Self::new(value, Mnemonic::DEC_C, 4, 0),
            0xE9 => Self::new(value, Mnemonic::JP_HL, 4, 0),
            0xD9 => Self::new(value, Mnemonic::RETI, 16, 0),
            0xEB => Self::new(value, Mnemonic::ILLEGAL_EB, 4, 0),
            0x86 => Self::new(value, Mnemonic::ADD_A_HL, 8, 0),
            0xF4 => Self::new(value, Mnemonic::ILLEGAL_F4, 4, 0),
            0x49 => Self::new(value, Mnemonic::LD_C_C, 4, 0),
            0xE3 => Self::new(value, Mnemonic::ILLEGAL_E3, 4, 0),
            0xDD => Self::new(value, Mnemonic::ILLEGAL_DD, 4, 0),
            0x60 => Self::new(value, Mnemonic::LD_H_B, 4, 0),
            0x7B => Self::new(value, Mnemonic::LD_A_E, 4, 0),
            0x98 => Self::new(value, Mnemonic::SBC_A_B, 4, 0),
            0x9A => Self::new(value, Mnemonic::SBC_A_D, 4, 0),
            0x12 => Self::new(value, Mnemonic::LD_DE_A, 8, 0),
            0x91 => Self::new(value, Mnemonic::SUB_A_C, 4, 0),
            0x11 => Self::new(value, Mnemonic::LD_DE_n16, 12, 2),
            0xA5 => Self::new(value, Mnemonic::AND_A_L, 4, 0),
            0xF8 => Self::new(value, Mnemonic::LD_HL_SP_e8, 12, 1),
            0x15 => Self::new(value, Mnemonic::DEC_D, 4, 0),
            0xAF => Self::new(value, Mnemonic::XOR_A_A, 4, 0),
            0xB8 => Self::new(value, Mnemonic::CP_A_B, 4, 0),
            0xE2 => Self::new(value, Mnemonic::LD_C_A, 8, 0),
            0x29 => Self::new(value, Mnemonic::ADD_HL_HL, 8, 0),
            0x22 => Self::new(value, Mnemonic::LD_HL_A, 8, 0),
            0x3A => Self::new(value, Mnemonic::LD_A_HL, 8, 0),
            0x47 => Self::new(value, Mnemonic::LD_B_A, 4, 0),
            0xFF => Self::new(value, Mnemonic::RST_38, 16, 0),
            0x2A => Self::new(value, Mnemonic::LD_A_HL, 8, 0),
            0x2C => Self::new(value, Mnemonic::INC_L, 4, 0),
            0x9B => Self::new(value, Mnemonic::SBC_A_E, 4, 0),
            0x35 => Self::new(value, Mnemonic::DEC_HL, 12, 0),
            0xCE => Self::new(value, Mnemonic::ADC_A_n8, 8, 1),
            0x96 => Self::new(value, Mnemonic::SUB_A_HL, 8, 0),
            0xC9 => Self::new(value, Mnemonic::RET, 16, 0),
            0x46 => Self::new(value, Mnemonic::LD_B_HL, 8, 0),
            0x2B => Self::new(value, Mnemonic::DEC_HL, 8, 0),
            0xC4 => Self::new(value, Mnemonic::CALL_NZ_a16, 24, 2),
            0xD6 => Self::new(value, Mnemonic::SUB_A_n8, 8, 1),
            0xA6 => Self::new(value, Mnemonic::AND_A_HL, 8, 0),
            0xDC => Self::new(value, Mnemonic::CALL_C_a16, 24, 2),
            0xEA => Self::new(value, Mnemonic::LD_a16_A, 16, 2),
            0x18 => Self::new(value, Mnemonic::JR_e8, 12, 1),
            0x97 => Self::new(value, Mnemonic::SUB_A_A, 4, 0),
            0xA3 => Self::new(value, Mnemonic::AND_A_E, 4, 0),
            0x81 => Self::new(value, Mnemonic::ADD_A_C, 4, 0),
            0x4E => Self::new(value, Mnemonic::LD_C_HL, 8, 0),
            0x1A => Self::new(value, Mnemonic::LD_A_DE, 8, 0),
            0x58 => Self::new(value, Mnemonic::LD_E_B, 4, 0),
            0x6B => Self::new(value, Mnemonic::LD_L_E, 4, 0),
            0x72 => Self::new(value, Mnemonic::LD_HL_D, 8, 0),
            0x27 => Self::new(value, Mnemonic::DAA, 4, 0),
            0xF2 => Self::new(value, Mnemonic::LD_A_C, 8, 0),
            0xBF => Self::new(value, Mnemonic::CP_A_A, 4, 0),
            0x76 => Self::new(value, Mnemonic::HALT, 4, 0),
            0x83 => Self::new(value, Mnemonic::ADD_A_E, 4, 0),
            0xA0 => Self::new(value, Mnemonic::AND_A_B, 4, 0),
            0xD1 => Self::new(value, Mnemonic::POP_DE, 12, 0),
            0xF1 => Self::new(value, Mnemonic::POP_AF, 12, 0),
            0x3B => Self::new(value, Mnemonic::DEC_SP, 8, 0),
            0x4C => Self::new(value, Mnemonic::LD_C_H, 4, 0),
            0x93 => Self::new(value, Mnemonic::SUB_A_E, 4, 0),
            0x26 => Self::new(value, Mnemonic::LD_H_n8, 8, 1),
            0xFB => Self::new(value, Mnemonic::EI, 4, 0),
            0xBC => Self::new(value, Mnemonic::CP_A_H, 4, 0),
            0xB4 => Self::new(value, Mnemonic::OR_A_H, 4, 0),
            0xBD => Self::new(value, Mnemonic::CP_A_L, 4, 0),
            0x07 => Self::new(value, Mnemonic::RLCA, 4, 0),
            0x00 => Self::new(value, Mnemonic::NOP, 4, 0),
            0x0F => Self::new(value, Mnemonic::RRCA, 4, 0),
            0xE7 => Self::new(value, Mnemonic::RST_20, 16, 0),
            0x2D => Self::new(value, Mnemonic::DEC_L, 4, 0),
            0x71 => Self::new(value, Mnemonic::LD_HL_C, 8, 0),
            0xE8 => Self::new(value, Mnemonic::ADD_SP_e8, 16, 1),
            0x99 => Self::new(value, Mnemonic::SBC_A_C, 4, 0),
            0x8C => Self::new(value, Mnemonic::ADC_A_H, 4, 0),
            0x1F => Self::new(value, Mnemonic::RRA, 4, 0),
            0x32 => Self::new(value, Mnemonic::LD_HL_A, 8, 0),
            0xD8 => Self::new(value, Mnemonic::RET_C, 20, 0),
            0xED => Self::new(value, Mnemonic::ILLEGAL_ED, 4, 0),
            0x16 => Self::new(value, Mnemonic::LD_D_n8, 8, 1),
            0x10 => Self::new(value, Mnemonic::STOP_n8, 4, 1),
            0x5C => Self::new(value, Mnemonic::LD_E_H, 4, 0),
            0x33 => Self::new(value, Mnemonic::INC_SP, 8, 0),
            0x5F => Self::new(value, Mnemonic::LD_E_A, 4, 0),
            0x64 => Self::new(value, Mnemonic::LD_H_H, 4, 0),
            0xA2 => Self::new(value, Mnemonic::AND_A_D, 4, 0),
            0xB9 => Self::new(value, Mnemonic::CP_A_C, 4, 0),
            0xBA => Self::new(value, Mnemonic::CP_A_D, 4, 0),
            0x23 => Self::new(value, Mnemonic::INC_HL, 8, 0),
            0x63 => Self::new(value, Mnemonic::LD_H_E, 4, 0),
            0xBE => Self::new(value, Mnemonic::CP_A_HL, 8, 0),
            0xFD => Self::new(value, Mnemonic::ILLEGAL_FD, 4, 0),
            0x8E => Self::new(value, Mnemonic::ADC_A_HL, 8, 0),
            0x04 => Self::new(value, Mnemonic::INC_B, 4, 0),
            0xAD => Self::new(value, Mnemonic::XOR_A_L, 4, 0),
            0xEF => Self::new(value, Mnemonic::RST_28, 16, 0),
            0xB7 => Self::new(value, Mnemonic::OR_A_A, 4, 0),
            0x31 => Self::new(value, Mnemonic::LD_SP_n16, 12, 2),
            0xB0 => Self::new(value, Mnemonic::OR_A_B, 4, 0),
            0x84 => Self::new(value, Mnemonic::ADD_A_H, 4, 0),
            0xB3 => Self::new(value, Mnemonic::OR_A_E, 4, 0),
            0x50 => Self::new(value, Mnemonic::LD_D_B, 4, 0),
            0x7A => Self::new(value, Mnemonic::LD_A_D, 4, 0),
            0x1C => Self::new(value, Mnemonic::INC_E, 4, 0),
            0xE5 => Self::new(value, Mnemonic::PUSH_HL, 16, 0),
            0x57 => Self::new(value, Mnemonic::LD_D_A, 4, 0),
            0x66 => Self::new(value, Mnemonic::LD_H_HL, 8, 0),
            0x1B => Self::new(value, Mnemonic::DEC_DE, 8, 0),
            0xAA => Self::new(value, Mnemonic::XOR_A_D, 4, 0),
            0x85 => Self::new(value, Mnemonic::ADD_A_L, 4, 0),
            0x9E => Self::new(value, Mnemonic::SBC_A_HL, 8, 0),
            0x94 => Self::new(value, Mnemonic::SUB_A_H, 4, 0),
            0x13 => Self::new(value, Mnemonic::INC_DE, 8, 0),
            0x80 => Self::new(value, Mnemonic::ADD_A_B, 4, 0),
            0x68 => Self::new(value, Mnemonic::LD_L_B, 4, 0),
            0x61 => Self::new(value, Mnemonic::LD_H_C, 4, 0),
            0xA1 => Self::new(value, Mnemonic::AND_A_C, 4, 0),
            0x5E => Self::new(value, Mnemonic::LD_E_HL, 8, 0),
            0x44 => Self::new(value, Mnemonic::LD_B_H, 4, 0),
            0x40 => Self::new(value, Mnemonic::LD_B_B, 4, 0),
            0xCD => Self::new(value, Mnemonic::CALL_a16, 24, 2),
            0xF7 => Self::new(value, Mnemonic::RST_30, 16, 0),
            0x65 => Self::new(value, Mnemonic::LD_H_L, 4, 0),
            0x02 => Self::new(value, Mnemonic::LD_BC_A, 8, 0),
            0xD2 => Self::new(value, Mnemonic::JP_NC_a16, 16, 2),
            0x54 => Self::new(value, Mnemonic::LD_D_H, 4, 0),
            0xDA => Self::new(value, Mnemonic::JP_C_a16, 16, 2),
            0x9C => Self::new(value, Mnemonic::SBC_A_H, 4, 0),
            0xA4 => Self::new(value, Mnemonic::AND_A_H, 4, 0),
            0xC5 => Self::new(value, Mnemonic::PUSH_BC, 16, 0),
            0x82 => Self::new(value, Mnemonic::ADD_A_D, 4, 0),
            0xF3 => Self::new(value, Mnemonic::DI, 4, 0),
            0xCF => Self::new(value, Mnemonic::RST_08, 16, 0),
            0x4A => Self::new(value, Mnemonic::LD_C_D, 4, 0),
            0xDE => Self::new(value, Mnemonic::SBC_A_n8, 8, 1),
            0x06 => Self::new(value, Mnemonic::LD_B_n8, 8, 1),
            0xA7 => Self::new(value, Mnemonic::AND_A_A, 4, 0),
            0x8B => Self::new(value, Mnemonic::ADC_A_E, 4, 0),
            0xD4 => Self::new(value, Mnemonic::CALL_NC_a16, 24, 2),
            0x20 => Self::new(value, Mnemonic::JR_NZ_e8, 12, 1),
            0x0B => Self::new(value, Mnemonic::DEC_BC, 8, 0),
            0x9D => Self::new(value, Mnemonic::SBC_A_L, 4, 0),
            0xC6 => Self::new(value, Mnemonic::ADD_A_n8, 8, 1),
            0x42 => Self::new(value, Mnemonic::LD_B_D, 4, 0),
            0xD5 => Self::new(value, Mnemonic::PUSH_DE, 16, 0),
            0xEE => Self::new(value, Mnemonic::XOR_A_n8, 8, 1),
            0x45 => Self::new(value, Mnemonic::LD_B_L, 4, 0),
            0x7C => Self::new(value, Mnemonic::LD_A_H, 4, 0),
            0x2F => Self::new(value, Mnemonic::CPL, 4, 0),
            0x1E => Self::new(value, Mnemonic::LD_E_n8, 8, 1),
            0x24 => Self::new(value, Mnemonic::INC_H, 4, 0),
            0xE6 => Self::new(value, Mnemonic::AND_A_n8, 8, 1),
            0x56 => Self::new(value, Mnemonic::LD_D_HL, 8, 0),
            0x8F => Self::new(value, Mnemonic::ADC_A_A, 4, 0),
            0xFE => Self::new(value, Mnemonic::CP_A_n8, 8, 1),
            0xF5 => Self::new(value, Mnemonic::PUSH_AF, 16, 0),
            0x0A => Self::new(value, Mnemonic::LD_A_BC, 8, 0),
            0x7F => Self::new(value, Mnemonic::LD_A_A, 4, 0),
            0x74 => Self::new(value, Mnemonic::LD_HL_H, 8, 0),
            0x4D => Self::new(value, Mnemonic::LD_C_L, 4, 0),
            0xB1 => Self::new(value, Mnemonic::OR_A_C, 4, 0),
            0x4F => Self::new(value, Mnemonic::LD_C_A, 4, 0),
            0xE1 => Self::new(value, Mnemonic::POP_HL, 12, 0),
            0xE4 => Self::new(value, Mnemonic::ILLEGAL_E4, 4, 0),
            0x6E => Self::new(value, Mnemonic::LD_L_HL, 8, 0),
            0x34 => Self::new(value, Mnemonic::INC_HL, 12, 0),
            0xB5 => Self::new(value, Mnemonic::OR_A_L, 4, 0),
            0x5D => Self::new(value, Mnemonic::LD_E_L, 4, 0),
            0x5B => Self::new(value, Mnemonic::LD_E_E, 4, 0),
            0xFA => Self::new(value, Mnemonic::LD_A_a16, 16, 2),
            0x5A => Self::new(value, Mnemonic::LD_E_D, 4, 0),
            0xAE => Self::new(value, Mnemonic::XOR_A_HL, 8, 0),
            0x09 => Self::new(value, Mnemonic::ADD_HL_BC, 8, 0),
            0x19 => Self::new(value, Mnemonic::ADD_HL_DE, 8, 0),
            0x90 => Self::new(value, Mnemonic::SUB_A_B, 4, 0),
            0xC0 => Self::new(value, Mnemonic::RET_NZ, 20, 0),
            0xF6 => Self::new(value, Mnemonic::OR_A_n8, 8, 1),
            0xC1 => Self::new(value, Mnemonic::POP_BC, 12, 0),
            0xA9 => Self::new(value, Mnemonic::XOR_A_C, 4, 0),
            0x2E => Self::new(value, Mnemonic::LD_L_n8, 8, 1),
            0xCC => Self::new(value, Mnemonic::CALL_Z_a16, 24, 2),
            0xAB => Self::new(value, Mnemonic::XOR_A_E, 4, 0),
            0x69 => Self::new(value, Mnemonic::LD_L_C, 4, 0),
            0x17 => Self::new(value, Mnemonic::RLA, 4, 0),
            0x79 => Self::new(value, Mnemonic::LD_A_C, 4, 0),
            0x9F => Self::new(value, Mnemonic::SBC_A_A, 4, 0),
            0x3F => Self::new(value, Mnemonic::CCF, 4, 0),
            0x6A => Self::new(value, Mnemonic::LD_L_D, 4, 0),
            0x48 => Self::new(value, Mnemonic::LD_C_B, 4, 0),
            0xD3 => Self::new(value, Mnemonic::ILLEGAL_D3, 4, 0),
            0x01 => Self::new(value, Mnemonic::LD_BC_n16, 12, 2),
            0x87 => Self::new(value, Mnemonic::ADD_A_A, 4, 0),
            0x75 => Self::new(value, Mnemonic::LD_HL_L, 8, 0),
            0x43 => Self::new(value, Mnemonic::LD_B_E, 4, 0),
            0x38 => Self::new(value, Mnemonic::JR_C_e8, 12, 1),
            0x05 => Self::new(value, Mnemonic::DEC_B, 4, 0),
            0xBB => Self::new(value, Mnemonic::CP_A_E, 4, 0),
            0x78 => Self::new(value, Mnemonic::LD_A_B, 4, 0),
            _ => Self::new(value, Mnemonic::NYI, 0, 0),
        }
    }
}
